# Định cấu hình cổng mặc định
port 6379

# Lắng nghe mọi kết nối (mặc định Redis chỉ nghe localhost)
bind 0.0.0.0

# Bật bảo vệ: giới hạn bộ nhớ tối đa mà Redis có thể sử dụng (256 Megabytes)
maxmemory 256mb

# Cấu hình "đuổi" các khóa (keys) ra khỏi bộ nhớ khi quá đầy
maxmemory-policy allkeys-lru

# (Tùy chọn) Đặt mật khẩu truy cập nếu thích, nếu thêm dòng này thì khi truy cập phải gõ lệnh AUTH my-secret-password
# requirepass my-secret-password
