spring.application.name=order-service

server.port=8083
server.address=0.0.0.0

# Load local .env when running from project directory
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:h2:mem:orderdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

clients.user-service.url=${USER_SERVICE_URL:http://localhost:8081}
clients.food-service.url=${FOOD_SERVICE_URL:http://localhost:8082}
internal.service-token=${SERVICE_TOKEN:svc-token-ktvtkpm-2026}
